### PR TITLE
big "content" update

### PR DESCRIPTION
**Pull request by Zarklord**
this update actually makes the "content" folder usefull by storing
picture font and sound assets along with a new color.xml(implemented by
me) that allows changing any of the usefull colors(to allow themed
versions without recompiling the rpx) i have included any missing assets for a black themed hbl and
also reorginized and removed some assets(for instance the hbl elf assets
are gone as its pointless to have those in the rpx branch)

### CODE REVIEW

**Comment by dimok789** [comment]
I want to keep the content compiled in as I plan to merge both branches (ELF and RPX version). If you want to commit your new images though, i will take a look at them.

**Comment by Yardape8000** [comment]
What if this was redone to check for data in content/themes/default and wiiu/apps/homebrew_launcher/themes/default?  If there was nothing there, it would use built-in data.
I think it would be great to be able to mod the look.  I would suggest it lead to a full theme.xml that allows changing icon size, layout, etc.

**Comment by dimok789** [comment]
Actually you are right. I did already have a check for the SD path. So I think I might add this pull request, revert the resource manager changes and only change the "custom resource path" in the Application.cpp

**Comment by Zarklord1** [comment]
it wouldnt be hard to have checks in many places like: 
in content 
in sd:wiiu/apps/hbl/resources(im to lazy to type the full path) 
in sd:/themes/hbl
or any other places...

**Comment by CreeperMario** [comment]
I just thought of something. Since the Wii's HBC is now open-source, I think it would be a good idea to follow in it's steps and allow themes to be installed into save data.

Just a thought. That I might look into. 😄

**Pull request closed without merging**
