### PR TITLE
Make the git repository self-contained

### PR DESCRIPTION
**Pull request by drizzt**

### CODE REVIEW

**Comment by dimok789** [comment]
I don't know about this. On the one hand it is nice to be independent of libwiiu on the other hand we want new fixes to be merged in automatically.

**Comment by drizzt** [comment]
yes if you use all the libwiiu feature, actually you are only using .h files.
moreover this commit can allow you use the travis like you do for loadiine

**Comment by bijita1** [comment]
when will there be an usb support

**Comment by bijita1** [comment]
and thanks for the hard work

**Comment by dimok789** [comment]
I think its ok as is. This header is only needed for payload generation and its nice to see it's origin.

**Pull request closed without merging**
